### PR TITLE
v8.0.0

### PR DESCRIPTION
**Pull request by mymindstorm**

### CODE REVIEW

**Comment by Sneezry** [comment]
Let's remove `short_name`

**Review by mymindstorm — COMMENTED** [review]
remove short_name from edge

**Comment by mymindstorm** [comment]
@Sneezry do you want it removed for Chrome and Firefox too?

**Comment by Sneezry** [comment]
It's okay to keep for Chrome and Firefox. There is still some issues for i18n. Some translations are empty strings. I have fixes that in Crowdin yesterday, but haven't update dev branch.

**Comment by mymindstorm** [comment]
@Sneezry good catch! I'll go ahead and push the changes.

**Comment by mymindstorm** [comment]
PR: #1258

**Review by Sneezry — APPROVED** [review]

**Pull request merged**
