### PR TITLE
Redo the stylesheet

### LINKED ISSUE #179: Refine style sheet

### PR DESCRIPTION
**Pull request by mymindstorm**
Closes #179 

- The main stylesheet is readable now
- Colors are a bit ugly since I can't just change normal variables on the fly, but now all colors can be changed from _ui.scss
- Update to Font Awesome 5

### CODE REVIEW

**Comment by Sneezry** [comment]
Cool. How do we get `css/solid.svg`? How should we update that file if we need new icon from fontawesome? Also, we need add original copyright info in that file.

**Comment by mymindstorm** [comment]
https://fontawesome.com/download -> sprites -> solid.svg in text editor -> ctrl + F icon-name -> copy and paste to our file

We already have an entry for Font Awesome in the about section, does it need to be updated?

**Comment by Sneezry** [comment]
Okay. Then is `sprites` in our tool chain? Such as script defined in pacakge.json or a script in script folder? Or add a guide about how to install this tool in README.

**Comment by mymindstorm** [comment]
sprites is a folder in the font awesome download

**Review by Sneezry — APPROVED** [review]

**Pull request merged**
