### PR TITLE
Try to prevent issues if chrome.storage.get unexpectedly returns undefined

### LINKED ISSUE #1215: Crash in chrome on v7
### Discussed in https://github.com/Authenticator-Extension/Authenticator/discussions/1212

<div type='discussions-op-text'>

<sup>Originally posted by **richardalger** June 20, 2024</sup>
A month ago everything was fine, and now when I need the code the extension does not open.
 
Screenshot 2024-06-20 203821
Screenshot 2024-06-20 203842
</div>

### PR DESCRIPTION
**Pull request by mymindstorm**
Attempt to fix #1215

### CODE REVIEW

**Comment by mymindstorm** [comment]
The CI is a problem with upstream. I've patched as a stopgap until https://github.com/mujo-code/puppeteer-headful/pull/134 gets merged. After this is merged, #1214 should also pass.

**Comment by Sneezry** [comment]
Is this a Chrome issue? chrome.storage.get should never return null or undefined. If it unexpectedly does, it could affect the account data. Is my understanding correct?

**Comment by mymindstorm** [comment]
It's documented that storage.get may cause managed storage get to return undefined. These parts of the code are the only calls which should generate the reported error messages.



This issue is very strange. I'm wondering if it might be a corrupted disk or bug in chrome. I'll keep searching for a root cause as you make a very good point.

 https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/get

-------- Original message --------
From: Zhe Li ***@***.***>
Date: 6/25/24 11:20 PM (GMT-06:00)
To: Authenticator-Extension/Authenticator ***@***.***>
Cc: Brendan Early ***@***.***>, Author ***@***.***>
Subject: Re: [Authenticator-Extension/Authenticator] Try to prevent issues if chrome.storage.get unexpectedly returns undefined (PR #1216)


Is this a Chrome issue? chrome.storage.get should never return null or undefined. If it unexpectedly does, it could affect the account data. Is my understanding correct?

**Comment by Sneezry** [comment]
Let's merge this PR first, and then continue exploring whether the unexpected results from reading the storage have any security impact on the account data.

**Review by Sneezry — APPROVED** [review]

**Pull request merged**
