### PR TITLE
update logo svg

### PR DESCRIPTION
**Pull request by mymindstorm**
Bringing it closer to the original. Not really sure how to add a stroke path without doubling up the opacity on the bottom shadow.

Docs for later: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons#SVG

### CODE REVIEW

**Comment by Sneezry** [comment]
I pushed some change to this branch. How about this one?

**Review by Sneezry — APPROVED** [review]

**Comment by mymindstorm** [comment]
Can't seem to make it more visible.

image

**Comment by Sneezry** [comment]
Changed border and shadow color to `#cccccc`

**Comment by mymindstorm** [comment]
So it turns out it just didn't want to render the stroke for some reason. The process to find that out was frustrating.

**Pull request merged**
