### PR TITLE
Add otpauth migration support

### PR DESCRIPTION
**Pull request by Sneezry**
#555

### CODE REVIEW

**Review by mymindstorm — APPROVED** [review]
Looks good, but I haven't had the time to test this just yet. I will open an issue later if I find anything.

**Review by mymindstorm — COMMENTED** [review]
Works perfectly, although it was not easy to get the QR onto my computer. It's a bit odd that only the import page allows this type of import, can we make this work via normal QR scanning?

**Comment by Sneezry** [comment]
> Works perfectly, although it was not easy to get the QR onto my computer. It's a bit odd that only the import page allows this type of import, can we make this work via normal QR scanning?

The QR code should be captured from mobile App, and transferred to computer. So I think it should be a local image file. Because we have already removed `file://*` permission, we are not able to scan local images via normal QR scanning.

**Comment by mymindstorm** [comment]
> > Works perfectly, although it was not easy to get the QR onto my computer. It's a bit odd that only the import page allows this type of import, can we make this work via normal QR scanning?
> 
> So I think it should be a local image file. Because we have already removed `file://*` permission, we are not able to scan local images via normal QR scanning.

There are some situations where this could happen, e.g. the screenshot is uploaded to Google drive and scanned in from the preview.

**Comment by Sneezry** [comment]
> > > Works perfectly, although it was not easy to get the QR onto my computer. It's a bit odd that only the import page allows this type of import, can we make this work via normal QR scanning?
> > 
> > 
> > So I think it should be a local image file. Because we have already removed `file://*` permission, we are not able to scan local images via normal QR scanning.
> 
> There are some situations where this could happen, e.g. the screenshot is uploaded to Google drive and scanned in from the preview.

Make sense. I will update the PR to add this feature.

**Comment by Sneezry** [comment]
I will make another PR for scanning migration QR code. Closing this one.

**Pull request merged**
