### PR TITLE
Search

### LINKED ISSUE #138: Seach feature
will be so hard add a search for this extensión?

### PR DESCRIPTION
**Pull request by mymindstorm**
closes #138 

Hit `/` to open search. Search bar will show if you have more than 10 accounts

I don't think the colors look that great. Do you have any better ideas on that front?

### CODE REVIEW

**Comment by Sneezry** [comment]
Should it be better if we hide the search bar by default?

**Comment by mymindstorm** [comment]
It should be hidden by defualt if you have less than 10 accounts.

**Comment by Sneezry** [comment]
screen shot 2018-06-20 at 11 21 59

It seems not on my side.

However, I find if the entries have been filtered in current tab, the search bar is hidden by default.

**Review by Sneezry — APPROVED** [review]

**Comment by mymindstorm** [comment]
Sorry, I don't think I communicated that very well. The search bar should only show up without the user calling it when a user has more than 10 accounts. Search should not show without user intervention if the user has more than 10 accounts and auto-filter is active. Search should not show if the user has less than 10 accounts.

Before this is merged, I want to discuss the following:

- Should the minimum number of accounts for search to show by default be raised higher?
- I don't think the color for the search bar is appropriate since it shouldn't grab attention. Additionally, the hotkey hint doesn't have much contrast with the current background color.

**Comment by gek15** [comment]
I

**Comment by gek15** [comment]
K

**Comment by gek15** [comment]
I

**Pull request merged**
