### PR TITLE
add jsqr license

### PR DESCRIPTION
**Pull request by Sneezry**

### CODE REVIEW

**Comment by mymindstorm** [comment]
The about page is pretty out of date, we need to redo it using the data in packages.json somehow (using the website and CI?). Something like [this](https://discord.com/licenses) would be nice. I'm going to try and throw something together.

**Comment by mymindstorm** [comment]
It's still a work-in-progress, what do you think?

https://mymindstorm.github.io/npm-license-generator/authenticator-licesnes

https://github.com/mymindstorm/npm-license-generator

**Comment by Sneezry** [comment]
Pretty cool!

**Comment by Sneezry** [comment]
One question, how about those dependencies not listed in package.json, such as font awesome

**Comment by mymindstorm** [comment]
There is an option to pass a custom template, we can just manually insert things that aren't in package.json.

**Pull request merged**
