### PR TITLE
5.0.6 dev to master

### PR DESCRIPTION
**Pull request by mymindstorm**
I'd like to push bugfix soon, anything else we need before pushing this?

### CODE REVIEW

**Comment by Sneezry** [comment]
Kindly remind: please use `Create a merge commit` rather than `Squash and merge` between `dev` and `master` branch, or our time will mess again.

snipaste20180305_103937

**Comment by mymindstorm** [comment]
I'm pretty sure you can disable squash merging in settings

**Comment by Sneezry** [comment]
I have no idea if I can disable squash merging on specific branch. When we need add new features, we create a new branch, and when the feature is ready, we squash merge it into `dev`, then delete the feature branch. But when we need merge `dev` into `master` or `master` into `release`, we need keep all commits. I can see merging settings in Merge button section, but it seems a global setting. Any idea?

**Comment by mymindstorm** [comment]
Nope, just checked. I really thought they would have a way to disable that on protected branches.

**Comment by Sneezry** [comment]
Not a big problem, we just know how to handle it now. Please merge master into release directly as well.

**Comment by mymindstorm** [comment]
Done, release tagged too. Uploading to AMO

**Pull request merged**
