### PR TITLE
Update French traductions

### PR DESCRIPTION
**Pull request by Starmania**
Update advisor string in French and refresh traduction file from Crowdin to GitHub

### CODE REVIEW

**Comment by Sneezry** [comment]
@Starmania Thank you for the contribution. You can update the translation on Crowdin, and we have a bot to sync code to GitHub. You don't need to do the sync manually.

**Comment by mymindstorm** [comment]
Hi @Starmania, please make this change in Crowdin instead. If you provide us your crowdin username, I can give you proofreader permissions.

**Comment by Starmania** [comment]
Same as GitHub, Starmania

**Comment by mymindstorm** [comment]
You now have proofreader permissions for French.

**Pull request closed without merging**
