### PR TITLE
add option to hide animated overlay when scanning qr code

### PR DESCRIPTION
**Pull request by jmlag**

### CODE REVIEW

**Comment by mymindstorm** [comment]
Thanks for the PR! Why do you want this option, is the overlay too annoying? How could we improve the overlay without adding an option?

**Comment by jmlag** [comment]
Yeah, it makes it hard to see what's on the screen; if you have a QR code in the middle of the screen, the QR code from the animation overlays it which is a bit confusing visually.

I would prefer removing the overlay altogether or replacing it with a text popup that fades away after a few seconds. 

If you don't want to do that, I'd recommend moving it to the upper-left corner, making it smaller, and reducing the opacity.

**Comment by mymindstorm** [comment]
What do you think about an opaque dialog that only shows on first scan with the animation and text? We could put a button at the bottom right to show it again.

**Comment by jmlag** [comment]
Seems like a good solution to me.

**Review by nguyendongduy — APPROVED** [review]

**Comment by mymindstorm** [comment]
Closing due to lack of response.

**Pull request closed without merging**
