### PR TITLE
Fix character encoding issue

### LINKED ISSUE #63: Setting non-standard characters in account fields breaks extension
Why when I try to open the program can only see a white window, and the codes do not appear?

### PR DESCRIPTION
**Pull request by mymindstorm**
should fix #63

### CODE REVIEW

**Comment by mymindstorm** [comment]
What do you think about this @Sneezry?

**Comment by Sneezry** [comment]
Looks good. Does it work? If it works, we can merge it.

**Comment by mymindstorm** [comment]
I tested and it worked, but you should test too when you have time.

**Comment by Sneezry** [comment]
Sure

**Comment by Sneezry** [comment]
It works on my side as well :-D

**Comment by mymindstorm** [comment]
Great!

**Pull request merged**
