### PR TITLE
Attempt to repair OTPStorage with missing keys

### LINKED ISSUE #57: Updating firefox version clears codes
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

Version disabled, investigating cause.

### PR DESCRIPTION
**Pull request by mymindstorm**
This attempts to re-initialize missing values from old version.

fixes #57

### CODE REVIEW

**Comment by Sneezry** [comment]
Oh, it seems we need a hotfix. The logic seems not correct, it only fix one property in the loop. As this is a hotfix, I will handle this issue to fix it fast.

**Comment by mymindstorm** [comment]
Its part of line 50's loop so it should loop through every property one at a time.

**Comment by mymindstorm** [comment]
@Sneezry 

https://github.com/Authenticator-Extension/Authenticator/blob/ad7e4310460bc1aa4c7f7d4ba791ca07186cb90e/src/models/storage.ts#L50

it should loop just fine

**Comment by Sneezry** [comment]
It is not only check valid issue, previous migrate logic is incorrect either. I have pushed the hotfix https://github.com/Authenticator-Extension/Authenticator/pull/59

**Comment by Sneezry** [comment]
Could you please post a wiki to tell user how to migrate data from old version to 5.0.4?

The user needs get raw data by `chrome.storage.sync.get(console.log)`, then copy the text and paste into import page.

**Comment by mymindstorm** [comment]
I can, but make it open a link to it if it detects that a user has old data

**Comment by Sneezry** [comment]
5.0.5 has been merged into release branch. I set 5.0.4 to push 1% user on Chrome for public preview, is there a similar option for Firefox market?

**Comment by mymindstorm** [comment]
No, I disabled the release completely as soon as I learned about the issue. Firefox updates are really slow, so I doubt much of the userbase have gotten it yet.

**Comment by mymindstorm** [comment]
So just so we are on the same page here, the old version was saving without some required keys. With your hotfix now users need to re-import? There isn't anything we can do to convert to new format without user intervention?

**Comment by Sneezry** [comment]
Not really. `EntryStorage.get` will handle migration:

https://github.com/Authenticator-Extension/Authenticator/blob/e993945612c44a2091439ba989b8853ce697fe54/src/models/storage.ts#L263

**Comment by mymindstorm** [comment]
Then we should get rid of 5.0.4 from distribution and ask any users that have problems with 5.0.4 to update to 5.0.5 instead of writing documentation?

**Comment by Sneezry** [comment]
As 5.0.5 is set to push to 1% user as well, I'm not sure they can get the update. However, 5.0.5 has been released to Chrome Web Store, and it weekend today, we can wait to see if any user post issues.

**Pull request closed without merging**
