### PR TITLE
use svg sector

### PR DESCRIPTION
**Pull request by Sneezry**
see https://github.com/Authenticator-Extension/Authenticator/issues/161

### CODE REVIEW

**Review by mymindstorm — CHANGES_REQUESTED** [review]
When using search padding gets doubled on some codes.

To repro, use this data and search `A`
```json
{
  "451599a5f9afa91a0f2097040a796f3d": {
    "account": "",
    "counter": 0,
    "encrypted": false,
    "hash": "451599a5f9afa91a0f2097040a796f3d",
    "index": 0,
    "issuer": "Secret A",
    "secret": "aaaaaaaaaaaaaa",
    "type": "totp"
  },
  "cf5b556dba671451882addb45ac2ce66": {
    "account": "",
    "counter": 0,
    "encrypted": false,
    "hash": "cf5b556dba671451882addb45ac2ce66",
    "index": 1,
    "issuer": "Secret B",
    "secret": "bbbbbbbbbbbbbbb",
    "type": "totp"
  },
  "e074e9f130abe0b4cfad490ef83a779f": {
    "account": "",
    "counter": 0,
    "encrypted": false,
    "hash": "e074e9f130abe0b4cfad490ef83a779f",
    "index": 2,
    "issuer": "Not Secret A",
    "secret": "bbbbbbbbbbbbbbbaaaa",
    "type": "totp"
  }
}
```

**Comment by Sneezry** [comment]
It seems fine on my side. Do I miss anything?

example

**Comment by mymindstorm** [comment]
It's present in your gif. I said padding by accident, I meant to say margin.

Normal (10px)
image

Abnormal (20px)

image

**Comment by Sneezry** [comment]
Got it

**Comment by alystair** [comment]
Looking good, thanks a bunch for implementing it! :+1:

**Pull request merged**
